[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc-version = "0.8.19"
via_ir = true
optimizer = true
optimizer-runs = 50

unchecked_cheatcode_artifacts = true

[rpc_endpoints]
telos-testnet = "https://testnet.telos.net/evm"
zeta-testnet = "https://rpc.ankr.com/zetachain_evm_athens_testnet"
shardeum-sphinx = "https://dapps.shardeum.org/"
anvil = "https://5929-35-232-110-246.ngrok-free.app"
linea = "https://rpc.linea.build"
linea-testnet = "https://rpc.goerli.linea.build"
zksync-testnet = "https://zksync-era-testnet.blockpi.network/v1/rpc/public"
zksync = "https://mainnet.era.zksync.io"
metachain-changi = "http://35.187.53.161:20551/"
scroll-sepolia = "https://sepolia-rpc.scroll.io/"
ethereum = "https://rpc.ankr.com/eth"
nova = "https://arbitrum-nova.blockpi.network/v1/rpc/public"
telos = "https://mainnet.telos.net/evm"
educhain = "https://open-campus-codex-sepolia.drpc.org"
